version: "3.9"
# Creamos tres réplicas y un balanceador de carga para la demo de disponibilidad
services:
  api1:
    build: .
    container_name: ut2_app1
    ports:
        - "8001:8000"
    environment:
      - REPLICA_NAME=Replica-1
  api2:
    build: .
    container_name: ut2_app2
    ports:
        - "8002:8000"
    environment:
      - REPLICA_NAME=Replica-2
  api3:
    build: .
    container_name: ut2_app3
    ports:
        - "8003:8000"
    environment:
      - REPLICA_NAME=Replica-3

  nginx:
    image: nginx:alpine
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
        - "8080:80"
    depends_on:
        - api1
        - api2
        - api3
